# Generated by Django 4.0.4 on 2022-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(auto_created=1, default=1, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('companyEmail', models.EmailField(max_length=50, verbose_name='Email Compañia')),
                ('personalEmail', models.EmailField(max_length=50, verbose_name='Email Personal')),
                ('active', models.BooleanField(max_length=50, verbose_name='Activo')),
                ('createdDate', models.DateField(max_length=50, verbose_name='Fecha de Creacion')),
                ('terminationDate', models.DateField(blank=True, max_length=50, null=True, verbose_name='Fecha de Finalizacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='GestionBaseDeDatos/static/images', verbose_name='Url Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Persona2',
            fields=[
                ('id', models.IntegerField(auto_created=1, default=1, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('companyEmail', models.EmailField(max_length=50, verbose_name='Email Compañia')),
                ('personalEmail', models.EmailField(max_length=50, verbose_name='Email Personal')),
                ('active', models.BooleanField(max_length=50, verbose_name='Activo')),
                ('createdDate', models.DateField(max_length=50, verbose_name='Fecha de Creacion')),
                ('terminationDate', models.DateField(blank=True, max_length=50, null=True, verbose_name='Fecha de Finalizacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='GestionBaseDeDatos/static/images', verbose_name='Url Imagen')),
            ],
        ),
    ]
