# Generated by Django 4.0.4 on 2022-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBaseDeDatos', '0003_alter_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='GestionBaseDeDatos/static/images/', verbose_name='Url Imagen'),
        ),
    ]
