# Generated by Django 4.0.4 on 2022-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBaseDeDatos', '0005_alter_persona_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Url Imagen'),
        ),
    ]
